apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  selector:
    app: webapp
    release: "0-5"

  type: NodePort # NodePort | ClusterIP  | LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 30080
