apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  selector:
    app: webapp

  type: NodePort   # NodePort | ClusterIP  | LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 30080


---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  selector:
    app: queue

  type: NodePort   # NodePort | ClusterIP  | LoadBalancer
  ports:
    - name: http
      port: 8161
      nodePort: 30010
